name: Deploy to dev environment AWS Account

on:
  workflow_dispatch:
    inputs:
      Action:
        description: "Select Terraform Action"
        required: true
        type: choice
        options:
          - apply
          - destroy
        default: apply

permissions:
  contents: read
  issues: write

jobs:
  plan-and-apply-dev:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: dev-self
      WORKING_DIR: Ecomm/aws-iac/eks
      Terraform_Backend_Configuration_File: tf_env/Backend_Dev_Config_Virginia.config
      Terraform_Deployment_Configuration_File: tf_env/Dev_Deployment.tfvars
      Action: ${{ github.event.inputs.Action }}
    secrets: inherit
