name: Deploy dev environment to Dev AWS Account

on:
  workflow_dispatch:

env:
  WORKING_DIR: ${{ github.workspace }}/Ecomm/Iac-aws/eks
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN_DEV }}

permissions:
  contents: read
  issues: write

jobs:
  plan-and-apply-dev:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: ./.github/workflows/deployment.yaml
    with:
      AWS_Deployment_Role_Arn: ${ { env.AWS_ROLE_ARN } }
      Terraform_Backend_Configuration_File: tf_env/Backend_Config_Virginia.config
      Terraform_Deployment_Configuration_File: tf_env/Dev_Deployment.tfvars
    secrets: inherit
