name: Deploy to dev environment AWS Account

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  plan-and-apply-dev:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: dev-self
      WORKING_DIR: Ecomm/aws-iac/eks
      Terraform_Backend_Configuration_File: tf_env/Backend_Dev_Config_Virginia.config
      Terraform_Deployment_Configuration_File: tf_env/Dev_Deployment.tfvars
      Action: destroy
    secrets: inherit
