name: Deploy uat edfx AWS Account

on:
  workflow_dispatch:
    

permissions:
  contents: read
  issues: write

jobs:
  plan-and-apply-dev:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: uat-edfx
      WORKING_DIR: Ecomm/aws-iac/eks
      Terraform_Backend_Configuration_File: tf_env/Backend_Uat_Config_Virginia.config
      Terraform_Deployment_Configuration_File: tf_env/Uat_Deployment.tfvars
      Action: destory
    secrets: inherit
    
